# -*- coding: utf-8 -*-
"""ABTest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r05qXhlsY0xyMk6znOh3KNq3Hwp2EBHO
"""

import pandas as pd
import requests
from scipy import stats
from statsmodels.stats.proportion import proportions_ztest

# 1. Load Cookie Cats Dataset from GitHub URL
# Dataset columns: userid, version (gate_30 / gate_40), sum_gamerounds, retention_1, retention_7
url = "https://raw.githubusercontent.com/jade1508/ab_testing/refs/heads/main/cookie_cats.csv"
df = pd.read_csv(url)

# 2. Extract sample sizes per group
n_gate30 = df[df["version"] == "gate_30"]["userid"].count()
n_gate40 = df[df["version"] == "gate_40"]["userid"].count()

# 3. Calculate 7-Day Retention Rates
retention_30 = df[df["version"] == "gate_30"]["retention_7"].sum()
retention_40 = df[df["version"] == "gate_40"]["retention_7"].sum()

cr_control = retention_30 / n_gate30
cr_treatment = retention_40 / n_gate40

# 4. Statistical Test for Uplift (Two-sample Z-Test for Proportions)
count = [retention_40, retention_30]
nobs = [n_gate40, n_gate30]
stat, p_value = proportions_ztest(count, nobs)

# 5. Check Sample Ratio Mismatch (SRM) via Chi-Square Test
# Expected ratio is 50/50 allocation
observed = [n_gate30, n_gate40]
expected = [(n_gate30 + n_gate40) / 2] * 2
_, p_srm = stats.chisquare(f_obs=observed, f_exp=expected)

# Package data payload
payload = {
    "Control_Group": "gate_30",
    "Treatment_Group": "gate_40",
    "CR_Control": round(float(cr_control), 4),
    "CR_Treatment": round(float(cr_treatment), 4),
    "P_Value": round(float(p_value), 4),
    "P_SRM": round(float(p_srm), 4),
}

# Automatically send metrics to make.com via webhook
make_webhook_url = "https://hook.eu1.make.com/xm6qdjhbr7yxr1tq2sy6cliyfsdxctwv"

response = requests.post(make_webhook_url, json=payload)

if response.status_code == 200:
    print("✅ Successfully sent test metrics to Make.com!")
else:
    print(f"❌ Failed to send. Status code: {response.status_code}")
